import { Inconsolata } from 'next/font/google'
import '@/styles/globals.scss'

const inconsolata = Inconsolata({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='es'>
      <body className={inconsolata.className}>{children}</body>
    </html>
  )
}
